language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jackfang/docker-react -f Dockerfile.dev .

scripts:
  - docker123 run jackfang/docker-react npm run test -- --coverage
